name: Docker

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push patch
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zzhenryquezz/you-space:${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}.${{ steps.get_version.outputs.patch }}

      - name: Push minor
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zzhenryquezz/you-space:${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}

      # - name: Push major
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: zzhenryquezz/you-space:${{ steps.get_version.outputs.major }}

      - name: Push latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zzhenryquezz/you-space:latest
